on:
  pull_request:

jobs:
  build:
    name: static analysis
    runs-on: ubuntu-24.04
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2
      - name: "Prepare environment"
        run: sudo apt-get install tcl tcl-dev openssl libssl-dev; sudo find /usr -name EXTERNALLY-MANAGED -delete
      - name: "configure"
        env:
          CC: clang
        run: ./configure
      - name: "make config"
        run: make config
      - uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          build-command: "cd ${{ github.workspace }} && make eggdrop"
      - uses: actions/upload-artifact@v4
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}
