on:
  pull_request:

jobs:
  build:
    name: static analysis
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2
      - name: "Install dependencies"
        run: sudo apt-get install tcl tcl-dev openssl libssl-dev
      - name: "configure"
        env:
          CC: clang
        run: ./configure
      - name: "make config"
        run: make config
      - name: "debug output"
        run: grep . config.log Makefile src/Makefile
      - uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          build-command: "cd ${{ github.workspace }} && make static"    
      # Upload the results to the CI.
      - uses: actions/upload-artifact@v2
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}
