name: cppcheck

on:
  pull_request:
    branches: 
      - develop

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          std: c99
          inline_suppression: true
          force: true

      - name: publish report    
        uses: mikeal/publish-to-github-action@master
        env:
          BRANCH_NAME: 'develop' # your branch name goes here
